---
- name: USER | create user `{{ _user.name }}`
  user:
    name: "{{ _user.name }}"
    create_home: "{{ _user.create_home | default(true) }}"
    append: true
    groups: "{{ _user.groups | default([]) }}"
    state: "{{ _user.enabled | ternary('present', 'absent') }}"
    shell: "{{ _user.shell | default('/bin/bash') }}"
    system: "{{ _user.system | default(false) | bool }}"
    update_password: always
    password: "{{ _user.password | default('') }}"
  become: true
  tags: [ create_user ]
