---
- name: VARS | merge users with defaults
  vars:
    _user: "{{ user_defaults | combine(item, recursive=True) }}"
  set_fact:
    _users: "{{ _users | default([]) + [ _user ] }}"
  loop: "{{ users }}"

- name: USER | DEBUG | users list content
  debug:
    var: _users
    verbosity: 1

- name: USER | create users
  include_tasks: create_users.yml
  loop: "{{ _users }}"
  loop_control:
    loop_var: _user

- name: SUDO | setup sudoers
  include_tasks: setup_sudoers.yml
  with_items: "{{ _users }}"
  loop_control:
    loop_var: _user

- name: SSH | setup ssh rsa authentication
  include_tasks: setup_key_auth.yml
  with_items: "{{ _users }}"
  loop_control:
    loop_var: _user

- name: PROMPT | setup prompt
  include_tasks: setup_prompt.yml
  with_items: "{{ _users }}"
  loop_control:
    loop_var: _user
