---
- block:
  - name: PROMPT | add extra functions to systemwide bashrc
    blockinfile:
      dest: "/etc/bashrc"
      create: true
      marker: "# {mark} extra functions managed by ansible"
      mode: 0644
      block: "{{ lookup('file', '../files/bash_functions') }}"
    become: true

  - name: PROMPT | setup bashrc for user `{{ _user.name }}`
    blockinfile:
      dest: ~/.bashrc
      marker: "# {mark} source /etc/bashrc"
      block: |
        if [ -f /etc/bashrc ]; then
          . /etc/bashrc
        fi
    become: true
    become_user: "{{ _user.name }}"
    when: ansible_os_family == 'Debian'

  - name: PROMPT | setup PS1 for user `{{ _user.name }}`
    blockinfile:
      create: true
      dest: ~/.bashrc
      marker: "# {mark} setup PS1 by ansible"
      mode: 0644
      block: "{{ lookup('file', '../files/prompt_command') }}"
    become: true
    become_user: "{{ _user.name }}"
    when: not _user.prompt.systemwide

  - name: PROMPT | setup PS1 systemwide
    blockinfile:
      dest: '/etc/bashrc'
      marker: "# {mark} setup PS1 by ansible"
      block: "{{ lookup('file', '../files/prompt_command') }}"
    become: true
    when: _user.prompt.systemwide

  - name: PROMPT | setup custom prompt when sudo for user `{{ _user.name }}`
    blockinfile:
      dest: '/etc/bashrc'
      marker: "# {mark} apply prompt when sudo"
      state: "{{ _user.enabled | ternary('present', 'absent') }}"
      block: "{{ lookup('template', '../templates/prompt_command') }}"
    become: true
    when: not _user.prompt.systemwide

  - name: PROMPT | Check if /etc/bash.bashrc exists
    stat:
      path: /etc/bash.bashrc
    register: bashbashrc

  - name: PROMPT | Apply /etc/bashrc from /etc/bash.bashrc `{{ _user.name }}`
    blockinfile:
      dest: '/etc/bash.bashrc'
      marker: "# {mark} apply prompt systemwide"
      state: "{{ _user.prompt.systemwide | ternary('present', 'absent') }}"
      block: "source /etc/bashrc"
    become: true
    when: bashbashrc.stat.exists

  when: _user.prompt.enabled and _user.enabled
  tags: [ setup_prompt ]
