---
- name: SSH | create .ssh directory for user `{{ _user.name }}`
  file:
    mode: 0700
    path: ~/.ssh
    state: "{{ _user.enabled | ternary('directory', 'absent') }}"
  when: _user.public_keys | length > 0
  become: true
  become_user: "{{ _user.name }}"
  tags: [ configure_ssh, cleanup ]

- name: SSH | put key to authorized_keys for user {{ _user.name }}
  authorized_key:
    user: "{{ _user.name }}"
    state: "{{ _user.enabled | ternary('present', 'absent') }}"
    key: "{{ item }}"

  loop: "{{ _user.public_keys }}"
  when: _user.public_keys | length > 0
  become: true
  become_user: "{{ _user.name }}"
  tags: [ configure_ssh, cleanup ]
