---
- block:
  - debug:
      var: _user
    tags: [create_user]

  - name: SUDO | add user `{{ _user.name }}` to `wheel` group
    user:
      name: "{{ _user.name }}"
      groups: wheel
      append: true
      state: present
    when: ansible_os_family == 'RedHat' and _user.sudo.enabled and
          not _user.sudo.passwordless
    tags: [ create_user ]

  - name: SUDO | add user `{{ _user.name }}` to passwordless sudoers
    lineinfile:
      dest: "/etc/sudoers.d/{{ _user.name }}"
      create: true
      owner: root
      group: root
      mode: 0640
      serole: object_r
      setype: etc_t
      line: "{{ _user.name }}     ALL=(ALL)       NOPASSWD: ALL"
    when: _user.sudo.passwordless
    tags: [ enable_passwordless_sudo ]

  become: true
  when: _user.enabled

- block:
  - name: SUDO | remove user `{{ _user.name }}` from `wheel` group
    user:
      name: "{{ _user.name }}"
      groups: wheel
      append: true
      state: absent
    when: ansible_os_family == 'RedHat' and _user.sudo.enabled and
          not _user.sudo.passwordless

  - name: SUDO | remove user `{{ _user.name }}` from passwordless sudoers
    file:
      dest: "/etc/sudoers.d/{{ _user.name }}"
      state: absent

  when: not _user.enabled
  become: true
  tags: [ cleanup ]
