---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos-7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true

  - name: centos-8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  # - name: fedora-25
  #   image: fedora:25
  # - name: fedora-26
  #   image: fedora:26
  # - name: fedora-27
  #   image: fedora:27
  # - name: debian-7-wheezy
  #   image: debian:wheezy
  # - name: debian-8-jessie
  #   image: debian:jessie
  # - name: debian-9-stretch
  #   image: debian:stretch
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible
